apiVersion: v1
kind: Service
metadata:
 name: graceful-shutdown-fast-api-service
spec:
 type: NodePort
 selector:
    app: graceful-shutdown-fast-api
 ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
